### ISSUE TITLE
pip install error on ubuntu:16.04

### ISSUE THREAD

**Issue by jesusch** [pixelb/ps_mem#45] opened 2018-11-14 10:53 UTC
while using pip install ps_mem I get the following error:
```
Collecting ps_mem
  Downloading https://files.pythonhosted.org/packages/46/81/ff8429735e2eb13be225dcfabef16d90bfa96b559e3f2643935d33b67697/ps_mem-3.12.tar.gz
Building wheels for collected packages: ps-mem
  Running setup.py bdist_wheel for ps-mem ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-YitmIm/ps-mem/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpNh95GJpip-wheel- --python-tag cp27:
  /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for ps-mem
  Running setup.py clean for ps-mem
Failed to build ps-mem
Installing collected packages: ps-mem
  Running setup.py install for ps-mem ... done
Successfully installed ps-mem-3.12
```

**Comment by jesusch** [comment] 2018-11-14 10:55
just fetching ps_mem.py and running it works fine

**Comment by parkerlreed** [comment] 2018-11-14 15:59
What version of pip? Looking online for this error I see mentions of this being caused by an outdated pip installation. You can have pip upgrade itself with

    pip install --upgrade pip

Also if you are already up to date, bdist_wheel is part of the wheel python package. Check if that's installed.

**Comment by pixelb** [comment] 2018-11-19 04:41
The top stackoverflow question presents many solutions to this,
so given it doesn't seem specific to ps_mem I'll close this here.
cheers

**Closed by pixelb** 2018-11-19 04:41 UTC
