### ISSUE TITLE
[Feature request] Set one memory usage dimension

### ISSUE THREAD

**Issue by MurzNN** [pixelb/ps_mem#32] opened 2017-06-01 05:52 UTC
At now script output size via most suitable dimension (MiB,KiB,GiB), but when comparing size there are not comfortable. Please add option for fix memory usage dimension, to show, for example, all numbers in Megabytes.

**Comment by allanlaal** [comment] 2022-10-19 01:34
#39 is a duplicate of #THIS

@MurzNN please change the title to: 

>[Feature request] Set one memory usage unit

**Comment by pixelb** [comment] 2022-10-21 14:09
Closing this. More details in #39

**Closed by pixelb** 2022-10-21 14:09 UTC
